/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemacontable.frames;

/**
 *
 * @author Ricky
 */
public class frmHome extends javax.swing.JFrame {

    /**
     * Creates new form frmHome
     */
    public frmHome() {
        initComponents();
        pnlComparar.setVisible(false);
        pnlNuevos.setVisible(false);
        pnlVer.setVisible(false);
        lbl1.setVisible(false);
        lbl2.setVisible(false);
        lbl3.setVisible(false);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblCerrar = new javax.swing.JLabel();
        lbl1 = new javax.swing.JLabel();
        lbl2 = new javax.swing.JLabel();
        lbl3 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        pnlComparar = new javax.swing.JPanel();
        lblBienvenida15 = new javax.swing.JLabel();
        lblBienvenida16 = new javax.swing.JLabel();
        lblBienvenida17 = new javax.swing.JLabel();
        lblBienvenida18 = new javax.swing.JLabel();
        pnlVer = new javax.swing.JPanel();
        lblBienvenida7 = new javax.swing.JLabel();
        lblBienvenida8 = new javax.swing.JLabel();
        lblBienvenida9 = new javax.swing.JLabel();
        lblBienvenida10 = new javax.swing.JLabel();
        pnlNuevos = new javax.swing.JPanel();
        lblBienvenida3 = new javax.swing.JLabel();
        lblBienvenida4 = new javax.swing.JLabel();
        lblBienvenida5 = new javax.swing.JLabel();
        lblBienvenida6 = new javax.swing.JLabel();
        lblComparar = new javax.swing.JLabel();
        lblCrearEstados = new javax.swing.JLabel();
        lblVerEstados = new javax.swing.JLabel();
        lblBienvenida = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblBienvenida1 = new javax.swing.JLabel();
        lblBienvenida2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(72, 165, 234));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCerrar.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        lblCerrar.setForeground(new java.awt.Color(255, 255, 255));
        lblCerrar.setText("x");
        lblCerrar.setToolTipText("Cerrar");
        lblCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCerrarMouseClicked(evt);
            }
        });
        jPanel1.add(lblCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 0, 10, -1));

        lbl1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Entypo_25be(0)_48.png"))); // NOI18N
        jPanel1.add(lbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 30, 20));

        lbl2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Entypo_25be(0)_48.png"))); // NOI18N
        jPanel1.add(lbl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, 30, 20));

        lbl3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Entypo_25be(0)_48.png"))); // NOI18N
        jPanel1.add(lbl3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 60, 30, 20));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 570, 30));

        pnlComparar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblBienvenida15.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        lblBienvenida15.setForeground(new java.awt.Color(51, 51, 51));
        lblBienvenida15.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblBienvenida15.setText("más eficientes.");
        pnlComparar.add(lblBienvenida15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 65, 390, 20));

        lblBienvenida16.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        lblBienvenida16.setForeground(new java.awt.Color(51, 51, 51));
        lblBienvenida16.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblBienvenida16.setText("Al tener 2 o más estados financieros en fechas distintas");
        pnlComparar.add(lblBienvenida16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 5, 390, 20));

        lblBienvenida17.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        lblBienvenida17.setForeground(new java.awt.Color(51, 51, 51));
        lblBienvenida17.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblBienvenida17.setText("de tu empresa, podrás hacer una comparación por medio");
        pnlComparar.add(lblBienvenida17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 25, 390, 20));

        lblBienvenida18.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        lblBienvenida18.setForeground(new java.awt.Color(51, 51, 51));
        lblBienvenida18.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblBienvenida18.setText("de los índices y así saber cuales períodos de fecha fueron");
        pnlComparar.add(lblBienvenida18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 45, 390, 20));

        jPanel1.add(pnlComparar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 410, 90));

        pnlVer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblBienvenida7.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        lblBienvenida7.setForeground(new java.awt.Color(51, 51, 51));
        lblBienvenida7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblBienvenida7.setText("para una fecha en específica.");
        pnlVer.add(lblBienvenida7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 65, 390, 20));

        lblBienvenida8.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        lblBienvenida8.setForeground(new java.awt.Color(51, 51, 51));
        lblBienvenida8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblBienvenida8.setText("Aquí están guardados todos los estados financieros de tu");
        pnlVer.add(lblBienvenida8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 5, 390, 20));

        lblBienvenida9.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        lblBienvenida9.setForeground(new java.awt.Color(51, 51, 51));
        lblBienvenida9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblBienvenida9.setText("empresa con la opción de seleccionarlos por una fecha.");
        pnlVer.add(lblBienvenida9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 25, 390, 20));

        lblBienvenida10.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        lblBienvenida10.setForeground(new java.awt.Color(51, 51, 51));
        lblBienvenida10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblBienvenida10.setText("Verás el balance general, estado de resultados y los índices");
        pnlVer.add(lblBienvenida10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 45, 390, 20));

        jPanel1.add(pnlVer, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 410, 90));

        pnlNuevos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblBienvenida3.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        lblBienvenida3.setForeground(new java.awt.Color(51, 51, 51));
        lblBienvenida3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblBienvenida3.setText("crear nuevos estados en un mismo mes.");
        pnlNuevos.add(lblBienvenida3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 65, 390, 20));

        lblBienvenida4.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        lblBienvenida4.setForeground(new java.awt.Color(51, 51, 51));
        lblBienvenida4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblBienvenida4.setText("Podrás crear nuevos estados financieros a partir de cuentas y sus");
        pnlNuevos.add(lblBienvenida4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 5, 390, 20));

        lblBienvenida5.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        lblBienvenida5.setForeground(new java.awt.Color(51, 51, 51));
        lblBienvenida5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblBienvenida5.setText("saldos. Cada vez que crees un estado financiero se guardará");
        pnlNuevos.add(lblBienvenida5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 25, 390, 20));

        lblBienvenida6.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        lblBienvenida6.setForeground(new java.awt.Color(51, 51, 51));
        lblBienvenida6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblBienvenida6.setText("para luego compararlo con fechas distintas. No es posible ");
        pnlNuevos.add(lblBienvenida6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 45, 390, 20));

        jPanel1.add(pnlNuevos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 410, 90));

        lblComparar.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        lblComparar.setForeground(new java.awt.Color(51, 51, 51));
        lblComparar.setText("Comparar Empresa");
        lblComparar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblComparar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCompararMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCompararMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCompararMouseExited(evt);
            }
        });
        jPanel1.add(lblComparar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, -1, 40));

        lblCrearEstados.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        lblCrearEstados.setForeground(new java.awt.Color(51, 51, 51));
        lblCrearEstados.setText("Crear Estados Financieros");
        lblCrearEstados.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCrearEstados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCrearEstadosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCrearEstadosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCrearEstadosMouseExited(evt);
            }
        });
        jPanel1.add(lblCrearEstados, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, 40));

        lblVerEstados.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        lblVerEstados.setForeground(new java.awt.Color(51, 51, 51));
        lblVerEstados.setText("Ver mis Estados");
        lblVerEstados.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblVerEstados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblVerEstadosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblVerEstadosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblVerEstadosMouseExited(evt);
            }
        });
        jPanel1.add(lblVerEstados, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, -1, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, 570, 450));

        lblBienvenida.setFont(new java.awt.Font("Segoe UI Light", 1, 36)); // NOI18N
        lblBienvenida.setForeground(new java.awt.Color(51, 51, 51));
        lblBienvenida.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBienvenida.setText("2017");
        getContentPane().add(lblBienvenida, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 150, 50));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 360, 20));

        lblBienvenida1.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        lblBienvenida1.setForeground(new java.awt.Color(51, 51, 51));
        lblBienvenida1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBienvenida1.setText("SISTEMA CONTABLE");
        getContentPane().add(lblBienvenida1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 280, 60));

        lblBienvenida2.setBackground(new java.awt.Color(72, 165, 234));
        lblBienvenida2.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        lblBienvenida2.setForeground(new java.awt.Color(72, 165, 234));
        lblBienvenida2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBienvenida2.setText("CASA");
        getContentPane().add(lblBienvenida2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 360, 40));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrarMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_lblCerrarMouseClicked

    private void lblCompararMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCompararMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblCompararMouseClicked

    private void lblCrearEstadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCrearEstadosMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblCrearEstadosMouseClicked

    private void lblVerEstadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVerEstadosMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblVerEstadosMouseClicked

    private void lblCrearEstadosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCrearEstadosMouseEntered
        pnlNuevos.setVisible(true);
        lbl1.setVisible(true);
    }//GEN-LAST:event_lblCrearEstadosMouseEntered

    private void lblCrearEstadosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCrearEstadosMouseExited
        pnlNuevos.setVisible(false);
        lbl1.setVisible(false);
    }//GEN-LAST:event_lblCrearEstadosMouseExited

    private void lblVerEstadosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVerEstadosMouseEntered
        pnlVer.setVisible(true);
        lbl2.setVisible(true);
    }//GEN-LAST:event_lblVerEstadosMouseEntered

    private void lblVerEstadosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVerEstadosMouseExited
        pnlVer.setVisible(false);
        lbl2.setVisible(false);
    }//GEN-LAST:event_lblVerEstadosMouseExited

    private void lblCompararMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCompararMouseEntered
        pnlComparar.setVisible(true);
        lbl3.setVisible(true);
    }//GEN-LAST:event_lblCompararMouseEntered

    private void lblCompararMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCompararMouseExited
        pnlComparar.setVisible(false);
        lbl3.setVisible(false);
    }//GEN-LAST:event_lblCompararMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lbl3;
    public static javax.swing.JLabel lblBienvenida;
    public static javax.swing.JLabel lblBienvenida1;
    public static javax.swing.JLabel lblBienvenida10;
    public static javax.swing.JLabel lblBienvenida15;
    public static javax.swing.JLabel lblBienvenida16;
    public static javax.swing.JLabel lblBienvenida17;
    public static javax.swing.JLabel lblBienvenida18;
    public static javax.swing.JLabel lblBienvenida2;
    public static javax.swing.JLabel lblBienvenida3;
    public static javax.swing.JLabel lblBienvenida4;
    public static javax.swing.JLabel lblBienvenida5;
    public static javax.swing.JLabel lblBienvenida6;
    public static javax.swing.JLabel lblBienvenida7;
    public static javax.swing.JLabel lblBienvenida8;
    public static javax.swing.JLabel lblBienvenida9;
    private javax.swing.JLabel lblCerrar;
    public static javax.swing.JLabel lblComparar;
    public static javax.swing.JLabel lblCrearEstados;
    public static javax.swing.JLabel lblVerEstados;
    private javax.swing.JPanel pnlComparar;
    private javax.swing.JPanel pnlNuevos;
    private javax.swing.JPanel pnlVer;
    // End of variables declaration//GEN-END:variables
}
