/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemacontable.frames;

/**
 *
 * @author Ricky
 */
public class frmHome extends javax.swing.JFrame {

    /**
     * Creates new form frmHome
     */
    public frmHome() {
        initComponents();
        pnlComparar.setVisible(false);
        pnlNuevos.setVisible(false);
        pnlVer.setVisible(false);
        lbl1.setVisible(false);
        lbl2.setVisible(false);
        lbl3.setVisible(false);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblCerrar = new javax.swing.JLabel();
        lblBienvenida2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        pnlComparar = new javax.swing.JPanel();
        lblBienvenida15 = new javax.swing.JLabel();
        lblBienvenida16 = new javax.swing.JLabel();
        lblBienvenida17 = new javax.swing.JLabel();
        lblBienvenida18 = new javax.swing.JLabel();
        pnlVer = new javax.swing.JPanel();
        lblBienvenida7 = new javax.swing.JLabel();
        lblBienvenida8 = new javax.swing.JLabel();
        lblBienvenida9 = new javax.swing.JLabel();
        lblBienvenida10 = new javax.swing.JLabel();
        pnlNuevos = new javax.swing.JPanel();
        lblBienvenida3 = new javax.swing.JLabel();
        lblBienvenida4 = new javax.swing.JLabel();
        lblBienvenida5 = new javax.swing.JLabel();
        lblBienvenida6 = new javax.swing.JLabel();
        lblBienvenida = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblBienvenida1 = new javax.swing.JLabel();
        btnComparar = new javax.swing.JButton();
        btnCrearEstados = new javax.swing.JButton();
        btnVerEstados = new javax.swing.JButton();
        lbl3 = new javax.swing.JLabel();
        lbl1 = new javax.swing.JLabel();
        lbl2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(72, 165, 234));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCerrar.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        lblCerrar.setForeground(new java.awt.Color(255, 255, 255));
        lblCerrar.setText("x");
        lblCerrar.setToolTipText("Cerrar");
        lblCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCerrarMouseClicked(evt);
            }
        });
        jPanel1.add(lblCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 0, 10, -1));

        lblBienvenida2.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        lblBienvenida2.setForeground(new java.awt.Color(255, 255, 255));
        lblBienvenida2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBienvenida2.setText("CASA");
        lblBienvenida2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBienvenida2MouseClicked(evt);
            }
        });
        jPanel1.add(lblBienvenida2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 470, 60));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 670, 30));

        pnlComparar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblBienvenida15.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        lblBienvenida15.setForeground(new java.awt.Color(51, 51, 51));
        lblBienvenida15.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblBienvenida15.setText("más eficientes.");
        pnlComparar.add(lblBienvenida15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 65, 390, 20));

        lblBienvenida16.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        lblBienvenida16.setForeground(new java.awt.Color(51, 51, 51));
        lblBienvenida16.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblBienvenida16.setText("Al tener 2 o más estados financieros en fechas distintas");
        pnlComparar.add(lblBienvenida16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 5, 390, 20));

        lblBienvenida17.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        lblBienvenida17.setForeground(new java.awt.Color(51, 51, 51));
        lblBienvenida17.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblBienvenida17.setText("de tu empresa, podrás hacer una comparación por medio");
        pnlComparar.add(lblBienvenida17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 25, 390, 20));

        lblBienvenida18.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        lblBienvenida18.setForeground(new java.awt.Color(51, 51, 51));
        lblBienvenida18.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblBienvenida18.setText("de los índices y así saber cuales períodos de fecha fueron");
        pnlComparar.add(lblBienvenida18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 45, 390, 20));

        jPanel1.add(pnlComparar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 420, 410, 90));

        pnlVer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblBienvenida7.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        lblBienvenida7.setForeground(new java.awt.Color(51, 51, 51));
        lblBienvenida7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblBienvenida7.setText("para una fecha en específica.");
        pnlVer.add(lblBienvenida7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 65, 390, 20));

        lblBienvenida8.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        lblBienvenida8.setForeground(new java.awt.Color(51, 51, 51));
        lblBienvenida8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblBienvenida8.setText("Aquí están guardados todos los estados financieros de tu");
        pnlVer.add(lblBienvenida8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 5, 390, 20));

        lblBienvenida9.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        lblBienvenida9.setForeground(new java.awt.Color(51, 51, 51));
        lblBienvenida9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblBienvenida9.setText("empresa con la opción de seleccionarlos por una fecha.");
        pnlVer.add(lblBienvenida9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 25, 390, 20));

        lblBienvenida10.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        lblBienvenida10.setForeground(new java.awt.Color(51, 51, 51));
        lblBienvenida10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblBienvenida10.setText("Verás el balance general, estado de resultados y los índices");
        pnlVer.add(lblBienvenida10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 45, 390, 20));

        jPanel1.add(pnlVer, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, 410, 90));

        pnlNuevos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblBienvenida3.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        lblBienvenida3.setForeground(new java.awt.Color(51, 51, 51));
        lblBienvenida3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblBienvenida3.setText("crear nuevos estados en un mismo mes.");
        pnlNuevos.add(lblBienvenida3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 65, 390, 20));

        lblBienvenida4.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        lblBienvenida4.setForeground(new java.awt.Color(51, 51, 51));
        lblBienvenida4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblBienvenida4.setText("Podrás crear nuevos estados financieros a partir de cuentas y sus");
        pnlNuevos.add(lblBienvenida4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 5, 390, 20));

        lblBienvenida5.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        lblBienvenida5.setForeground(new java.awt.Color(51, 51, 51));
        lblBienvenida5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblBienvenida5.setText("saldos. Cada vez que crees un estado financiero se guardará");
        pnlNuevos.add(lblBienvenida5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 25, 390, 20));

        lblBienvenida6.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        lblBienvenida6.setForeground(new java.awt.Color(51, 51, 51));
        lblBienvenida6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblBienvenida6.setText("para luego compararlo con fechas distintas. No es posible ");
        pnlNuevos.add(lblBienvenida6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 45, 390, 20));

        jPanel1.add(pnlNuevos, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 410, 90));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 0, 570, 700));

        lblBienvenida.setFont(new java.awt.Font("Segoe UI Light", 1, 36)); // NOI18N
        lblBienvenida.setForeground(new java.awt.Color(51, 51, 51));
        lblBienvenida.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBienvenida.setText("2017");
        lblBienvenida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBienvenidaMouseClicked(evt);
            }
        });
        getContentPane().add(lblBienvenida, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 150, 70));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 430, 20));

        lblBienvenida1.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        lblBienvenida1.setForeground(new java.awt.Color(51, 51, 51));
        lblBienvenida1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBienvenida1.setText("SISTEMA CONTABLE");
        lblBienvenida1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBienvenida1MouseClicked(evt);
            }
        });
        getContentPane().add(lblBienvenida1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 310, 60));

        btnComparar.setBackground(new java.awt.Color(57, 137, 186));
        btnComparar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnComparar.setForeground(new java.awt.Color(72, 165, 234));
        btnComparar.setText("Comparar Empresa");
        btnComparar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(72, 165, 234)));
        btnComparar.setContentAreaFilled(false);
        btnComparar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnComparar.setFocusPainted(false);
        btnComparar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCompararMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCompararMouseExited(evt);
            }
        });
        btnComparar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompararActionPerformed(evt);
            }
        });
        getContentPane().add(btnComparar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 440, 260, 50));

        btnCrearEstados.setBackground(new java.awt.Color(57, 137, 186));
        btnCrearEstados.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCrearEstados.setForeground(new java.awt.Color(72, 165, 234));
        btnCrearEstados.setText("Crear nuevos Estados Financieros");
        btnCrearEstados.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(72, 165, 234)));
        btnCrearEstados.setContentAreaFilled(false);
        btnCrearEstados.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCrearEstados.setFocusPainted(false);
        btnCrearEstados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCrearEstadosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCrearEstadosMouseExited(evt);
            }
        });
        btnCrearEstados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearEstadosActionPerformed(evt);
            }
        });
        getContentPane().add(btnCrearEstados, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 260, 50));

        btnVerEstados.setBackground(new java.awt.Color(57, 137, 186));
        btnVerEstados.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnVerEstados.setForeground(new java.awt.Color(72, 165, 234));
        btnVerEstados.setText("Ver mis Estados Financieros");
        btnVerEstados.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(72, 165, 234)));
        btnVerEstados.setContentAreaFilled(false);
        btnVerEstados.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVerEstados.setFocusPainted(false);
        btnVerEstados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnVerEstadosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnVerEstadosMouseExited(evt);
            }
        });
        btnVerEstados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerEstadosActionPerformed(evt);
            }
        });
        getContentPane().add(btnVerEstados, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, 260, 50));

        lbl3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Entypo_25b8(0)_48.png"))); // NOI18N
        getContentPane().add(lbl3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, 40, 50));

        lbl1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Entypo_25b8(0)_48.png"))); // NOI18N
        getContentPane().add(lbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 40, 50));

        lbl2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Entypo_25b8(0)_48.png"))); // NOI18N
        getContentPane().add(lbl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 40, 50));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrarMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_lblCerrarMouseClicked

    private void lblBienvenidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBienvenidaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblBienvenidaMouseClicked

    private void lblBienvenida1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBienvenida1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblBienvenida1MouseClicked

    private void lblBienvenida2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBienvenida2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblBienvenida2MouseClicked

    private void btnCompararActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompararActionPerformed

    }//GEN-LAST:event_btnCompararActionPerformed

    private void btnCrearEstadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearEstadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCrearEstadosActionPerformed

    private void btnVerEstadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerEstadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVerEstadosActionPerformed

    private void btnCrearEstadosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearEstadosMouseEntered
        pnlNuevos.setVisible(true);
        lbl1.setVisible(true);
    }//GEN-LAST:event_btnCrearEstadosMouseEntered

    private void btnCrearEstadosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearEstadosMouseExited
        pnlNuevos.setVisible(false);
        lbl1.setVisible(false);
    }//GEN-LAST:event_btnCrearEstadosMouseExited

    private void btnVerEstadosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVerEstadosMouseEntered
        pnlVer.setVisible(true);
        lbl2.setVisible(true);
    }//GEN-LAST:event_btnVerEstadosMouseEntered

    private void btnVerEstadosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVerEstadosMouseExited
        pnlVer.setVisible(false);
        lbl2.setVisible(false);
    }//GEN-LAST:event_btnVerEstadosMouseExited

    private void btnCompararMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCompararMouseEntered
        pnlComparar.setVisible(true);
        lbl3.setVisible(true);
    }//GEN-LAST:event_btnCompararMouseEntered

    private void btnCompararMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCompararMouseExited
        pnlComparar.setVisible(false);
        lbl3.setVisible(false);
    }//GEN-LAST:event_btnCompararMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnComparar;
    private javax.swing.JButton btnCrearEstados;
    private javax.swing.JButton btnVerEstados;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lbl3;
    public static javax.swing.JLabel lblBienvenida;
    public static javax.swing.JLabel lblBienvenida1;
    public static javax.swing.JLabel lblBienvenida10;
    public static javax.swing.JLabel lblBienvenida15;
    public static javax.swing.JLabel lblBienvenida16;
    public static javax.swing.JLabel lblBienvenida17;
    public static javax.swing.JLabel lblBienvenida18;
    public static javax.swing.JLabel lblBienvenida2;
    public static javax.swing.JLabel lblBienvenida3;
    public static javax.swing.JLabel lblBienvenida4;
    public static javax.swing.JLabel lblBienvenida5;
    public static javax.swing.JLabel lblBienvenida6;
    public static javax.swing.JLabel lblBienvenida7;
    public static javax.swing.JLabel lblBienvenida8;
    public static javax.swing.JLabel lblBienvenida9;
    private javax.swing.JLabel lblCerrar;
    private javax.swing.JPanel pnlComparar;
    private javax.swing.JPanel pnlNuevos;
    private javax.swing.JPanel pnlVer;
    // End of variables declaration//GEN-END:variables
}
