/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemacontable.frames;

import clases.ControladorCuenta;
import clases.Cuenta;
import clases.ErrorSistemaContable;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Enrique
 */
public class frmModificarCuentas extends javax.swing.JFrame {

    int idEmpresa=0;
    public frmModificarCuentas() {
        initComponents();
//        cargandoTabla("",cmbEstados.getSelectedIndex()+1,fechaAnio.getYear(),idEmpresa);
    }
    
    public void cargandoTabla(String cuenta,int idFinanciero,int anio,int idEmpresa){
        
        
        DefaultTableModel modeloTabla=new DefaultTableModel();
        
        ArrayList<Cuenta> misCuentas=new ArrayList<Cuenta>();
        Object [] fila=new Object[3];
        String[] campos = {"Id Cuenta", "Cuenta", "Valor"};
        try {
            modeloTabla.setColumnIdentifiers(campos);
            misCuentas=ControladorCuenta.FiltroCuentas(cuenta,idFinanciero,anio,idEmpresa);
            Iterator ite=misCuentas.iterator();
            while (ite.hasNext()) {
                fila[0]=ite.next();
                fila[1]=ite.next();
                fila[2]=ite.next();
                modeloTabla.addRow(fila);
            }
            tblCuentas.setModel(modeloTabla);
        } catch (ErrorSistemaContable ex) {
            Logger.getLogger(frmModificarCuentas.class.getName()).log(Level.SEVERE, null, ex);
        
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNombreEmpresa = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cmbEstados = new javax.swing.JComboBox<>();
        fechaAnio = new com.toedter.calendar.JYearChooser();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtCuenta = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCuentas = new javax.swing.JTable();
        btnModificar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNombreEmpresa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lblNombreEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 60, 220, 30));

        jLabel2.setText("AÑO:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, -1, -1));

        cmbEstados.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbEstadosItemStateChanged(evt);
            }
        });
        getContentPane().add(cmbEstados, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, 200, -1));
        getContentPane().add(fechaAnio, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 80, -1));

        jLabel3.setText("ESTADOS FINANCIEROS: ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));

        jLabel4.setText("BUSCAR CUENTA:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, -1, -1));

        txtCuenta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCuentaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCuentaKeyTyped(evt);
            }
        });
        getContentPane().add(txtCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 450, -1));

        tblCuentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Id Cuenta", "Cuenta", "Valor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblCuentas);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 880, 240));

        btnModificar.setText("MODIFICAR");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        getContentPane().add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 460, -1, -1));

        jLabel5.setText("MODIFICAR CUENTAS");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 20, -1, -1));

        jLabel6.setText("EMPRESA");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 40, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCuentaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCuentaKeyReleased
        String cuenta=txtCuenta.getText();
        int idFinanciero=cmbEstados.getSelectedIndex()+1;
        int anio=fechaAnio.getYear();
        
        
        try {
            idEmpresa=ControladorCuenta.ObtenerIDEmpresa(lblNombreEmpresa.getText());
            cargandoTabla(cuenta,idFinanciero,anio,idEmpresa);
        } catch (ErrorSistemaContable ex) {
            Logger.getLogger(frmModificarCuentas.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_txtCuentaKeyReleased

    private void txtCuentaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCuentaKeyTyped
        char mayu=evt.getKeyChar();
        if (Character.isLowerCase(mayu)) {
            String cadena=(""+mayu).toUpperCase();
            mayu=cadena.charAt(0);
            evt.setKeyChar(mayu);
        }
        else{

        }
    }//GEN-LAST:event_txtCuentaKeyTyped

    private void cmbEstadosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbEstadosItemStateChanged

    }//GEN-LAST:event_cmbEstadosItemStateChanged

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        if(tblCuentas.getSelectedRow()!=-1){
            int seleccion; 
            frmModificandoCuenta pm = new frmModificandoCuenta();
            pm.setVisible(true);
//            this.dispose();
            seleccion = tblCuentas.getSelectedRow();
            pm.txtId.setText(tblCuentas.getValueAt(seleccion, 0).toString());
            pm.txtNombre.setText((tblCuentas.getValueAt(seleccion, 1).toString()));
            pm.txtValor.setText((tblCuentas.getValueAt(seleccion, 2).toString()));
            
            
            pm.txtNombre.requestFocus();
            pm.txtNombre.selectAll();
            pm.txtId.setEnabled(false);
            pm.setLocationRelativeTo(null);
        }else{
            JOptionPane.showMessageDialog(null, "Selecciones un dato de la tabla por favor" );
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmModificarCuentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmModificarCuentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmModificarCuentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmModificarCuentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmModificarCuentas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnModificar;
    public javax.swing.JComboBox<String> cmbEstados;
    private com.toedter.calendar.JYearChooser fechaAnio;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JLabel lblNombreEmpresa;
    private javax.swing.JTable tblCuentas;
    public javax.swing.JTextField txtCuenta;
    // End of variables declaration//GEN-END:variables
}
